### ISSUE TITLE
Develop solutions for the bech32 problem @ Terra Classic & Terra v2

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/feather.js#1]
**Problem definition**
Fork TFL Interchain wallet, develop potential solutions to the bech32 problem at the wallet level, and present multiple solutions to TFL.

**Feature specification**
TODO - Spec

**Additional context**
- [ ] Clear 100% of backlog. (Required dependency)
- [ ] Develop framework for solution.  Prefix with network?
- [ ] Develop governance proposal
- [ ] Review governance outcome
 
**Acceptance Criteria**
- Achieve consensus with TFL
- Ensure solution works with all participants in network
- Solution Deployed

**Comment by inon-man** [comment]
May I ask what the bech32 problem is?

**Comment by fragwuerdig** [comment]
TFL are currently developing the interchain station wallet. Interchain requests using this wallet are routed based on the bech32 prefix. Terra Classic and Terra v2 have the same bech32 prefix (i.e. terra). This makes it impossible to use Terra Classic with the interchain wallet from TFL.

**Comment by inon-man** [comment]
@fragwuerdig I see. Can I understand the scope of problem exists in interchain wallet?

**Comment by edk208** [comment]
TFL will include LUNC into interchain wallet with the upgrade of the chain to cosmos v45, IBCs open to LUNA, and some sort of fix to the bech32.  The change of LUNC from the prefix "terra" to "terrac" was the original ask from TFL, but I think that is not feasible, at least in the short term.  TFL is exploring other ways to get around the bech32 routing, and it was added into our task list to also look at different ways in parallel.  This could be in cooperation with TFL or independently.

**Comment by inon-man** [comment]
we may ask TFL to make separate scheme rule instead of relying on bech32 prefix 
i.e.
network:bech32
with the routing table for networks

**Comment by edk208** [comment]
yes I think we can ask.  But they have told us several times that they have a much smaller team and are completely overwhelmed with a lot of their new initiatives.  If we have spare cycles, it may be worthwhile offering to either coordinate with them, or just do it for them and present it as an option.

**Comment by LuncBurner** [comment]
[_] Clear 100% of backlog. (Required dependency)
[_] Develop framework for solution.  Prefix with network?
[_] Develop governance proposal
[_] Review governance outcome
 
Acceptance Critera
- Achieve consensus with TFL
- Ensure solution works with all participants in network
- Deploy Solution

**Comment by edk208** [comment]
not necessary anymore

**Comment by LuncBurner** [comment]
@edk208 I've seen the news circulating on Twitter that the Interchain Wallet will support Luna Classic.  Will be interesting to see if this is the case.
